# Generated by Django 2.1.5 on 2019-02-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190208_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerexam',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='user',
            new_name='owner',
        ),
    ]
