# Generated by Django 2.1.5 on 2019-02-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupa',
        ),
    ]
